# Generated by Django 3.0.6 on 2020-05-18 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name_text', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CityName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name_text', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_text', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name_text', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('mod_date', models.DateTimeField(verbose_name='date modified')),
                ('restaurant_address', models.CharField(max_length=200)),
                ('restaurant_comment', models.CharField(max_length=300)),
                ('city_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.CityArea')),
                ('restaurant_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.CityName')),
                ('restaurant_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name_text', models.CharField(max_length=100)),
                ('menu_comment_text', models.CharField(max_length=300)),
                ('sub_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='cityarea',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.CityName'),
        ),
    ]
