# Generated by Django 3.0.6 on 2020-05-21 18:29

from django.db import migrations, models
import django.db.models.deletion
import info_edit.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name_text', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CityName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name_text', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_text', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name_text', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('mod_date', models.DateTimeField(verbose_name='date modified')),
                ('restaurant_address', models.CharField(max_length=200)),
                ('restaurant_comment', models.CharField(blank=True, max_length=300)),
                ('image_num', models.IntegerField(default=0)),
                ('city_area', models.ManyToManyField(to='info_edit.CityArea')),
                ('restaurant_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.CityName')),
                ('restaurant_genre', models.ManyToManyField(to='info_edit.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name_text', models.CharField(max_length=100)),
                ('menu_comment_text', models.CharField(max_length=300)),
                ('menu_price', models.IntegerField(blank=True, default=0)),
                ('image_num', models.IntegerField(default=0)),
                ('sub_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to=info_edit.models.make_upload_path)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('sub_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to=info_edit.models.make_menu_upload_path)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('sub_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.RestaurantMenu')),
            ],
        ),
        migrations.AddField(
            model_name='cityarea',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.CityName'),
        ),
    ]
