# Generated by Django 3.0.6 on 2020-05-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_edit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='menu_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_comment',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
