# Generated by Django 3.0.6 on 2020-05-19 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_edit', '0002_auto_20200518_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalRImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='original_images/')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info_edit.OriginalRImages'),
        ),
    ]
