# Generated by Django 3.0.6 on 2020-05-19 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_edit', '0003_auto_20200519_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalMImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='original_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_images',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_num',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.OriginalRImages')),
                ('sub_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.OriginalMImages')),
                ('sub_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_edit.RestaurantMenu')),
            ],
        ),
    ]
