# Generated by Django 3.0.6 on 2020-05-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_edit', '0005_auto_20200519_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuimage',
            name='original_image',
        ),
    ]
