# Generated by Django 3.0.6 on 2020-05-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_edit', '0006_remove_menuimage_original_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OriginalMImages',
        ),
        migrations.DeleteModel(
            name='OriginalRImages',
        ),
    ]
