# Generated by Django 3.0.6 on 2020-05-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_edit', '0008_auto_20200520_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='image_num',
            field=models.IntegerField(default=0),
        ),
    ]
